### ISSUE TITLE
Clicking "Save" creates empty django.mo file if django.po does not exist

### ISSUE THREAD

**Issue by etamponi** [boxed/okrand#2]
**To reproduce:**
1) Pick a language for which you still don't have a django.po file (eg: locale/it)
1) Translate a few strings into that language using the Okrand UI
1) click "Save"

**Expected:**
- locale/it/LC_MESSAGES/django.mo contains some data

**Actual:**
- locale/it/LC_MESSAGES/django.mo is empty
- All translations are lost!

**Comment by boxed** [comment]
If I didn't have the directory I got #6

**Comment by boxed** [comment]
Released 1.1.3 that I believe fixes this.
