### ISSUE TITLE
How do I use the translations?

### ISSUE THREAD

**Issue by etamponi** [boxed/okrand#3]
I translated a bunch of messages in Italian. Then I go to the admin site, but all the strings are still in English... Do I need an extra step to use the translations?

**Comment by etamponi** [comment]
It looks like Okrand is putting the locale at the root of the project instead of inside the app directory. Using LOCALE_PATHS fixed this. But is this the desired behavior?

**Comment by boxed** [comment]
Hm.. I honestly don't know. I wrote Okrand for my own personal use and there I have LOCALE_PATHS set. I guess at the very least Okrand should present an error if it's not set in that case, what do you think?

**Comment by etamponi** [comment]
I noticed that makemessages has exactly the same behavior, so I'd say it's fine to leave this as it is :)

**Comment by boxed** [comment]
Oh, well that's a bit of a relief then :P
